from .ochreserializer import OchreSerializer

from .permissionsserializer import PermissionsSerializer

from .userserializer import UserSerializer
from .userinteractiveserializer import UserInteractiveSerializer

from .courseserializer import CourseSerializer

from .researchprojectserializer import ResearchProjectSerializer

from .researchartifactserializer import ResearchArtifactSerializer
from .researchartifactinteractiveserializer import ResearchArtifactInteractiveSerializer

from .articleserializer import ArticleSerializer

#from .documentationserializer import DocumentationSerializer
#from .documentationinteractiveserializer import DocumentationInteractiveSerializer

from .pageserializer import PageSerializer
from .fileserializer import FileSerializer
#from .slideserializer import SlideSerializer
#from .slideinteractiveserializer import SlideInteractiveSerializer
#from .slideuploadserializer import SlideUploadSerializer

from .ontologyserializer import OntologySerializer
from .ontologyinteractiveserializer import OntologyInteractiveSerializer

from .materialserializer import MaterialSerializer
from .materialinteractiveserializer import MaterialInteractiveSerializer

from .primarysourceserializer import PrimarySourceSerializer
from .primarysourceinteractiveserializer import PrimarySourceInteractiveSerializer
from .primarysourcehathitrustserializer import PrimarySourceHathiTrustSerializer
from .primarysourcexsltransformationserializer import PrimarySourceXslTransformationSerializer

from .primarysourcematerialsserializer import PrimarySourceMaterialsSerializer
from .primarysourcefinalizematerialsserializer import PrimarySourceFinalizeMaterialsSerializer

from .queryserializer import QuerySerializer
from .queryinteractiveserializer import QueryInteractiveSerializer
from .queryfromfileserializer import QueryFromFileSerializer
from .queryfromtextserializer import QueryFromTextSerializer


from .annotationserializer import AnnotationSerializer
from .annotationinteractiveserializer import AnnotationInteractiveSerializer
from .annotationcomputationalserializer import AnnotationComputationalSerializer
from .annotationhumanserializer import AnnotationHumanSerializer

from .machinelearningmodelserializer import MachineLearningModelSerializer
from .machinelearningmodelinteractiveserializer import MachineLearningModelInteractiveSerializer
from .machinelearningmodeltopicmodelserializer import MachineLearningModelTopicModelSerializer
from .machinelearningmodelhuggingfaceserializer import MachineLearningModelHuggingfaceSerializer
from .machinelearningmodelstarcoderserializer import MachineLearningModelStarcoderSerializer
