from .ochreviewset import OchreViewSet
from .primarysourceviewset import PrimarySourceViewSet
from .materialviewset import MaterialViewSet
from .ontologyviewset import OntologyViewSet
from .permissionsviewset import PermissionsViewSet
from .documentationviewset import DocumentationViewSet
from .userviewset import UserViewSet
from .machinelearningmodelviewset import MachineLearningModelViewSet
from .queryviewset import QueryViewSet
#from .slideviewset import SlideViewSet
from .articleviewset import ArticleViewSet
from .researchartifactviewset import ResearchArtifactViewSet
from .researchprojectviewset import ResearchProjectViewSet
from .courseviewset import CourseViewSet
from .annotationviewset import AnnotationViewSet
