# Generated by Django 4.0.10 on 2023-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0002_remove_annotation_source_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='primarysource',
        ),
        migrations.AddField(
            model_name='annotation',
            name='primarysources',
            field=models.ManyToManyField(to='ochre.primarysource'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='queries',
            field=models.ManyToManyField(to='ochre.query'),
        ),
    ]
