# Generated by Django 4.2 on 2023-04-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0003_remove_annotation_primarysource_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_annotation_unique_name_and_user'),
        ),
        migrations.AddConstraint(
            model_name='machinelearningmodel',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_machinelearningmodel_unique_name_and_user'),
        ),
        migrations.AddConstraint(
            model_name='primarysource',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_primarysource_unique_name_and_user'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_query_unique_name_and_user'),
        ),
    ]
