# Generated by Django 4.2 on 2023-04-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0004_annotation_ochre_annotation_unique_name_and_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentation',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_documentation_unique_name_and_user'),
        ),
        migrations.AddConstraint(
            model_name='researchartifact',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_researchartifact_unique_name_and_user'),
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_slide_unique_name_and_user'),
        ),
    ]
