# Generated by Django 4.2 on 2023-06-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0008_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='machinelearningmodel',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ochre.machinelearningmodel'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='primarysource',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ochre.primarysource'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotator', to=settings.AUTH_USER_MODEL),
        ),
    ]
