# Generated by Django 4.2 on 2023-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0009_alter_annotation_machinelearningmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
