# Generated by Django 4.2 on 2023-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0010_user_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchartifact',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
