# Generated by Django 4.2 on 2023-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0011_researchartifact_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchartifact',
            name='recording',
            field=models.FileField(null=True, upload_to='research/recordings'),
        ),
    ]
