# Generated by Django 4.2 on 2023-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0014_alter_researchartifact_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchartifact',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
