# Generated by Django 4.2 on 2023-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0015_alter_researchartifact_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchartifact',
            name='title',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
