# Generated by Django 4.2 on 2023-07-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0017_rename_description_user_research_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
