# Generated by Django 4.2 on 2023-07-18 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0018_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('name', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ordering', models.IntegerField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instructors', models.ManyToManyField(related_name='teaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='creators',
            field=models.ManyToManyField(related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='image',
            field=models.ImageField(null=True, upload_to='slides'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='researchers',
            field=models.ManyToManyField(related_name='participates_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_course_unique_name_and_user'),
        ),
    ]
