# Generated by Django 4.2 on 2023-07-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0020_researchproject_artifacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='researchproject',
            old_name='active',
            new_name='is_active',
        ),
    ]
