# Generated by Django 4.2 on 2023-07-28 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0022_article_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='courses',
            field=models.ManyToManyField(related_name='mentioned_in', to='ochre.course'),
        ),
        migrations.AddField(
            model_name='article',
            name='researchartifacts',
            field=models.ManyToManyField(related_name='mentioned_in', to='ochre.researchartifact'),
        ),
        migrations.AddField(
            model_name='article',
            name='researchprojects',
            field=models.ManyToManyField(related_name='mentioned_in', to='ochre.researchproject'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='article_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='researchproject_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='appendix',
            field=models.FileField(null=True, upload_to='researchartifact/appendices'),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='document',
            field=models.FileField(null=True, upload_to='researchartifact/documents'),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='image',
            field=models.ImageField(null=True, upload_to='researchartifact/images'),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='recording',
            field=models.FileField(null=True, upload_to='researchartifact/recordings'),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='slides',
            field=models.FileField(null=True, upload_to='researchartifact/slides'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='artifacts',
            field=models.ManyToManyField(related_name='derived_from', to='ochre.researchartifact'),
        ),
    ]
