# Generated by Django 4.2 on 2023-08-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0025_remove_researchartifact_creators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='people',
        ),
    ]
