# Generated by Django 4.2 on 2023-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0026_rename_users_article_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='artifacts',
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='related_to',
            field=models.ManyToManyField(related_name='contributed_to', to='ochre.researchproject'),
        ),
    ]
