# Generated by Django 4.2 on 2023-08-03 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0027_remove_researchproject_artifacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\s*\\+?[\\d\\s\\-]+$')]),
        ),
    ]
