# Generated by Django 4.2 on 2023-08-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0028_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
