# Generated by Django 4.2 on 2023-08-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0029_researchproject_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchartifact',
            name='related_to',
            field=models.ManyToManyField(related_name='produced', to='ochre.researchproject'),
        ),
    ]
