# Generated by Django 4.2 on 2023-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0030_alter_researchartifact_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
