# Generated by Django 4.2 on 2023-12-24 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0033_banner_delete_documentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('name', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('banner_overlay', models.TextField(blank=True, default='')),
                ('banner_image', models.ImageField(upload_to='banners')),
                ('description', models.TextField(blank=True, default='')),
                ('dynamic_content_view', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pages',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='ochre_page_unique_name_and_user'),
        ),
    ]
