# Generated by Django 4.2 on 2023-12-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0034_page_delete_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
