# Generated by Django 4.2 on 2023-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0035_alter_page_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='machinelearningmodel',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='primarysource',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'queries'},
        ),
        migrations.AlterModelOptions(
            name='researchproject',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='page',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_top_level',
            field=models.BooleanField(default=False),
        ),
    ]
