# Generated by Django 4.2 on 2023-12-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0036_alter_annotation_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='primarysource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='query',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='researchartifact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='is_active',
        ),
    ]
