# Generated by Django 4.2 on 2023-12-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0038_file_file_ochre_file_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(upload_to='user_uploads'),
        ),
    ]
