# Generated by Django 4.2 on 2023-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochre', '0039_alter_file_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
